import React from 'react'

const About = () => {
    return (
        <React.Fragment>
            <div style={{ fontSize: '40px', fontWeight:'bold' }}>About</div>
            <p>
                Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris pellentesque odio eu elementum volutpat. Etiam vitae iaculis nisl, ac aliquet mauris. Donec et risus nec nulla ultrices posuere nec sed nunc. Etiam non mollis velit. Donec ut justo sed quam tincidunt elementum. Sed et convallis nisl, vitae aliquam mauris. Vivamus nec nunc sem. Mauris molestie efficitur porttitor. Praesent fermentum id leo non pharetra. Fusce nec consectetur lacus. Donec commodo nunc quis ornare scelerisque. Nulla vulputate vel metus id ultrices. Sed malesuada hendrerit feugiat. Praesent porta eros ut ligula convallis, eu fringilla erat porta.

                Nam quis finibus tellus. Praesent molestie ligula et suscipit sodales. In sit amet egestas sem. Phasellus eget risus semper, lobortis felis non, posuere nisi. Interdum et malesuada fames ac ante ipsum primis in faucibus. Integer fermentum nibh justo, vel pretium dui ornare vitae. Integer ullamcorper leo leo, a gravida ipsum vestibulum eu. Fusce quis blandit purus, at bibendum tortor.

                Curabitur quis suscipit dui, ut rutrum lectus. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed gravida rutrum orci, sed iaculis lacus convallis non. Ut vel lectus nulla. Phasellus sodales dictum malesuada. Suspendisse vehicula vestibulum nunc sed faucibus. Donec eget bibendum erat. Ut dignissim justo sed nisi fermentum, ut interdum turpis dapibus. Nullam scelerisque, risus id viverra elementum, odio eros tristique dolor, eget sodales leo nunc et neque. Aliquam erat volutpat. Ut ullamcorper auctor erat, a ullamcorper lorem facilisis vitae. Vestibulum sagittis mi augue, a elementum dolor mattis id. Proin volutpat tincidunt mauris, eu egestas ligula fringilla a. Aenean dapibus cursus purus, a vehicula ex varius vel. Nullam mattis congue augue eget convallis.

                Maecenas id eros lobortis, lobortis tellus eu, vulputate mi. Nunc vel metus pellentesque, fringilla est quis, blandit dolor. Sed lobortis vitae dolor eu rhoncus. Sed nec iaculis neque, bibendum consequat ex. Curabitur scelerisque vehicula euismod. Donec efficitur commodo cursus. Aliquam pharetra bibendum magna. Etiam dictum, erat feugiat fermentum auctor, eros ante porttitor lacus, vestibulum bibendum mi libero ac velit. Nunc pellentesque fringilla erat in auctor. Nullam iaculis nunc nunc, eget malesuada velit porta sit amet. Vivamus aliquam felis mi, ut porta nunc dignissim a. Nunc id tellus porta, aliquam enim sed, euismod felis.

                Proin sed enim at nulla porttitor semper. Pellentesque iaculis nisi vitae auctor volutpat. Morbi blandit ex massa, gravida molestie lectus mollis commodo. Aenean nisl tortor, convallis vitae venenatis sed, scelerisque vel lacus. Donec blandit bibendum libero nec fermentum. Proin blandit turpis et dignissim pellentesque. Curabitur ultricies purus non iaculis tempor. Vestibulum feugiat erat eget maximus fringilla.

                Duis tincidunt ante ut felis vulputate, id consequat ligula luctus. Mauris euismod ac ante id fringilla. Nullam non dolor fringilla, scelerisque dui volutpat, fermentum ante. Curabitur eleifend, elit et tempus venenatis, neque neque viverra massa, in viverra est neque accumsan orci. Integer feugiat a erat ut finibus. Nam sed ex nec lorem molestie tempor non eu magna. Ut lorem lectus, auctor non enim efficitur, commodo dapibus quam. Fusce dictum condimentum rhoncus. Phasellus sed nisi tortor. Nam commodo risus ut nisi ornare luctus. Sed aliquet arcu a erat volutpat lobortis. Nulla aliquam mi sit amet mi congue venenatis. Morbi in dolor at urna hendrerit commodo. Nam sit amet tellus massa. Cras eu massa eu ipsum blandit blandit a sit amet ante.

                Nam vitae tincidunt metus, quis suscipit augue. Suspendisse faucibus felis gravida nisl porta, vel feugiat felis dignissim. Praesent viverra mollis mi quis facilisis. Quisque id commodo sem. Etiam libero sapien, laoreet vel faucibus ac, convallis nec risus. Aliquam eget est auctor purus mollis placerat ac ac erat. Nullam augue odio, lobortis a aliquet ac, ullamcorper eget mauris. Integer feugiat ultricies dolor quis fermentum. Ut placerat ipsum vitae volutpat vestibulum. Duis dignissim dui vel nisl congue venenatis. Pellentesque et ornare neque. Nullam volutpat, velit sit amet rhoncus semper, magna est aliquam justo, vitae tincidunt mauris odio at nisi.

                Nam convallis mauris massa, quis mattis magna interdum at. Phasellus tellus nunc, semper vel urna in, suscipit lobortis mi. Nulla sed nisi facilisis, placerat purus in, tincidunt sapien. Suspendisse nec suscipit nunc. Aliquam ex eros, laoreet in egestas aliquet, aliquam a orci. Sed fermentum sit amet lectus vel dignissim. Curabitur bibendum lacinia suscipit. Donec sit amet tempor urna. Pellentesque fermentum ante et augue malesuada, sed mattis massa hendrerit. Fusce eros tortor, consectetur ullamcorper mauris at, rutrum ultrices metus. Aliquam mollis sapien non sem interdum cursus. Curabitur ultrices interdum nulla, ut fringilla nisl placerat nec. Maecenas vel bibendum justo, sit amet posuere lacus. Mauris vitae risus magna. Ut libero eros, rutrum nec gravida sed, vulputate consequat metus. Quisque eget metus vulputate nibh suscipit sagittis.

                Ut at ipsum a metus viverra mollis. Sed quis condimentum dui. Proin tristique semper ante in efficitur. Aenean iaculis pretium tellus ac volutpat. Maecenas aliquam risus eros, in ultricies nisi euismod at. Aliquam a nisi nec tellus tempor sollicitudin at at massa. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla non mauris egestas, varius elit a, tincidunt mi. Sed ultricies lacinia tortor, pellentesque volutpat massa lobortis nec. Donec placerat metus at nulla ornare, quis pharetra est accumsan. Proin posuere nec lacus ullamcorper rutrum. Aenean faucibus lectus ante, eu lobortis purus finibus id. Vestibulum interdum erat nec metus commodo mattis. Nunc volutpat, neque non efficitur dictum, lectus lacus bibendum quam, vel vestibulum velit dui non risus.

                Phasellus tempor eros non ipsum consequat bibendum. Suspendisse sed nunc sodales, ullamcorper felis id, tincidunt augue. In hac habitasse platea dictumst. Nunc a aliquam odio, in porttitor ipsum. Proin vel varius risus. Integer laoreet sem nec ornare varius. Nam viverra ex vel dolor pharetra iaculis. Nulla facilisi. Sed eu enim facilisis, feugiat turpis sed, accumsan libero. Fusce ornare nunc a porta dictum. Phasellus metus elit, vestibulum a arcu eu, consequat dapibus orci. Vestibulum lobortis ipsum sed nibh venenatis fermentum ac eu tortor.
            </p>
        </React.Fragment>

    )
}

export default About